utreexo/utreexo

accumulator_test.go
TestUndo would only be able to test on initial pollards that never had a
deletion performed. This refactor allows testing of undos for pollards
that has had a deletion now.
Previously we can only have these pollards to start off of:
02
|---\
00  01
14
|---------------\
12              13
|-------\       |-------\
08      09      10      11
|---\   |---\   |---\   |---\
00  01  02  03  04  05  06  07
Now we can have these pollards to start off of:
02
|---\
14
|---------------\
12              13
|-------\       |-------\
10      11
|---\   |---\   |---\   |---\
06  07
=> accumulator_test: Refactor TestUndo

accumulator_test.go
posMapSanity() now also checks that the map has as much entries as there
are leaves in the accumulator.
=> accumulator_test: Check element count in posMapSanity

prove.go
calculateRoots now calls toHashAndPos itself so the caller doesn't need
to do so. The passed in proof is no longer mutated as well.
=> prove: Refactor calculateRoots

utils.go
Both isAncestor and calcNextPosition functions are required for doing
pollard modifications with proofs.
=> utils: Add isAncestor() and calcNextPosition()

prove.go
proofAfterDeletion function takes in a proof and returns a new proof
that can be used to calculate what the roots would be after the deletion
of the targets in the current proof has happened.
This function is useful in calculating the roots of the accumulator in a
purely functional way.
=> prove: Add proofAfterDeletion function

prove.go
The roots are organized from the greatest position to the smallest in
pollard. However in calculateRoots, since we're hashing from the
smallest position to the greatest and appending calculated roots along
the way, the roots are in smallest to greatest order. Reversing makes
the roots in the same order as how the roots are organized in pollard.
=> prove: Reverse the rootCandidates in calculateRoots

.gitignore
I ran the tests and a test coverage report file(`.cov`) is created that need not be pushed to the repository.
Is there anything else that should be added to the `.gitignore` file?
=> gitignore: add .gitignore

prove.go
There were two mergeSortedSlices functions for two different types of
slices. We can have one function if we use generics.
The mergeSortedNodeAndPos wasn't used but I'm leaving making the
mergeSortedSlices function generic nonetheless as this library is going
through a lot of change and more flexiblility is worth it at the moment.
=> prove: Have one generic mergeSortedSlices

utils.go
Adding a simple util function for debugging.
=> util: Add hashAndPosToString()

prove.go, utils.go
The slice subtraction operations are refactored out into
subtractSortedSlice() improving readability and reuseability.
=> prove: Add subtractSortedSlice()

prove.go, prove_test.go
proofAfterDeletion only allowed for deleting all the targets in a proof.
However, if we want to modify proof for a wallet, we need the ability to
only delete select targets in a proof. ProofAfterPartialDeletion allows
for that and we keep proofAfterDeletion as a wrapper around
proofAfterPartialDeletion, still allowing callers to call without the
delHashes for the proof when deleting all the targets.
=> prove: Refactor proofAfterDeletion into proofAfterPartialDeletion

prove.go, prove_test.go, testdata/fuzz/FuzzModifyProofChain/1fc7b95197fbb08cffd57ec6c152588b0430c8e495ad93a88101b0abe86ced38, testdata/fuzz/FuzzModifyProofChain/a97a7763d8a175119a4bf09d83eb00818a9843225617147a259e7ec8cbe0f541, testdata/fuzz/FuzzModifyProofChain/b434ec4bd98125133b367643e13caf87446f83b5ea8abc6a3f401cfab2e61836, testdata/fuzz/FuzzModifyProofChain/d4dabb8690862a1e3669d43e45dd60cf793966de3fe60703fa944f5b2bac64d6, testdata/fuzz/FuzzModifyProofChain/e2eadb5145649872c41f8450921aa52b505b4aaff8cdc886918583170e82648f, testdata/fuzz/FuzzModifyProofChain/e9339d530284a0f604f198c9b1ee9d96c0f4f16e0afc90ff748115a42976b623, utils.go
ModifyProof acts as a modify function for proofs, updating the cached
proof so that it verifies after the deletions and the additions that
happen in a block
=> prove: Add ModifyProof

accumulator.go, accumulator_test.go, testdata/fuzz/FuzzWriteAndRead/6c92720246f9663600833d40ab0b9a1c17617e8a0aa4ca6a03e9c76466cc4228
Enables Pollard to be written and restored from the disk (or any
interface that satisfies io.Reader and io.Writer.
=> accumulator: Write and Restore functionality for Pollard

prove.go, utils.go
UpdateProofAdd is now refactored into smaller functions, improving
readability.
=> prove: Refactor UpdateProofAdd()

prove.go, prove_test.go
A separate slice of uint32s can now be passed into proof modification
which indicate the hashes that should be cached in the cached proof.
=> prove: Add remember to proof additions

stump.go
Verify() now returns the indexes of the matched roots instead of the
calculated roots. This allows the deletion function for stump to
avoid the loop where it tries to find which roots need to be updated.
=> stump: Simplify the stump deletion

prove.go, prove_test.go, stump.go, stump_test.go
Update() now returns UpdateData struct which contains all the data needed from the stump to update a cached proof.
=> Stump: Return UpdateData on Update

prove.go, prove_test.go, testdata/fuzz/FuzzModifyProofChain/0a745837de0b3b29665de16ab9977c07130c9d30931992430786e6ec47f40500, testdata/fuzz/FuzzModifyProofChain/0f60e322f9d2fa084cdb0228d2ad73aa7fb4f0a9b24b9314a569fc9f9184ee94, testdata/fuzz/FuzzModifyProofChain/24ef5fcd199d83f1616d3e2e0d52b8b7fd10407663ad64cd5fb7c64703de8830, testdata/fuzz/FuzzModifyProofChain/7738fbe1f2d5eb92da4cfbb9c74fa26709843214ef71be318395b9e5219600c2, testdata/fuzz/FuzzModifyProofChain/dd77e26b789d4135e2508bb59f72a38280caf11b9ce723135b1e6bc0dee94e56, testdata/fuzz/FuzzModifyProofChain/e6a266cf7828677fe974230f85980354fc83faeb5f47cbce72dbd197c1a271bd, testdata/fuzz/FuzzModifyProofChain/eb4299435353bbbab6873b4c8125d74ba0e5926ff901451c6a0f4587be6640af, utils.go
UpdateProof is now a method on a Proof struct and now no longer does
extra hashing while updating the proof.
=> Prove: Refactor UpdateProof

README.md
While playing around with the library I noticed that the code example in README.md is seemingly outdated. This PR fixes that with the following changes:
- add missing boolean argument for utreexo.NewAccumulator(...) call
- in addition to []utreexo.Hash, also create []utreexo.Leaf, as this is expected by Pollard's Modify method (which we use to add elements)
- fix argument for call to cachedProof.Update(...) (s/remembers/rememberIndexes)
- fix return value assignment of utreexo.Verify (returns two values, error is at second place)
- avoid redeclaring updateData (use operator "=" instead of ":=")
Verified this by running https://gist.github.com/theStack/53e5a5c8b31d78d54b5cf427868e6bf3. Maybe on the long-term it would make sense to just include the example as file which is also run as part …
=> fix README.md code example

utils.go
printLeaves allow for easy human-readable printing of a slice of Leaf struct.
=> accumulator/utils: add printleaves

utils.go
rootExistsOnRow provides a cheap calculation to check if there is a root on the given row with the given num leaves.
=> accumulator/utils: add rootExistsOnRow

pollard_test.go
The FuzzModify code logic is refactored into fuzzModify() function which will take in a UtreexoTest interface. This allows the test to be re-used for different Utreexo implmenetations.
=> utreexo/pollard_test: refactor FuzzModify

pollard_test.go
The FuzzUndoChain code logic is refactored into fuzzUndoChain() function which will take in a UtreexoTest interface. This allows the test to be re-used for different Utreexo implmenetations.
=> utreexo/pollard_test: refactor FuzzUndoChain

utils.go, utils_test.go
rootPositions returns all the positions of the roots in the given numleaves and total rows.
=> utreexo/utils: add rootPositions

utils.go, utils_test.go
inForest checks that a position exists within the accumulator with the given numleaves and total rows.
=> utreexo/util: add inForest

mappollard.go, mappollard_test.go
Prune method allows the caller to selectively un-cache targets from the accumulator. Only the proofs that are no longer needed are pruned so that all the other cached targets are still provable.
=> mappollard: add Prune method

mappollard.go, mappollard_test.go
For p2p communication where a peer explicitly asks for the hashes it needs, there needs to be accumulator support returning what positions a node is missing to be able to prove certain leaves.
GetMissingPositions provides that functionality by returning the positions of the hashes it's missing in ascending order.
=> mappollard: add GetMissingPositions

mappollard.go
For callers, it is possible to call multiple methods on mappollard at the same time and have the runtime panic as there's concurrent map accesses. Putting in a mutex solves this issue.
=> mappollard: fix concurrency bugs

mappollard.go
For Undo(), mappollard was assuming that there weren't nodes to fetch from since not all of the leaves are cached. But since full caches everything, we don't need this assumption. The changes here make it possible to Undo with just the targets of the proof and not the full proof.
=> mappollard: support full mappollard for Undo

mappollard.go, mappollard_test.go, prove.go, prove_test.go, stump_test.go, utils.go, utils_test.go
=> Revert "utils: simplify and export proofpositions"

mappollard.go, mappollard_test.go
We refactor and use getLeafHashPositions to make sure all the exported functions will return translated positions on return.
=> mappollard: make sure to translate positions for GetLeafHashPositions

mappollard.go, polnode.go, utils.go, utils_test.go
Exporting these functions as they're needed by utreexod.
=> Export childMany, leftChild, and rightChild

mappollard.go, mappollard_test.go, pollard.go, polnode.go, prove.go, stump.go, utils.go, utils_test.go
Exporting these as they're needed by the utreexod library.
=> Export parent util functions

pollard.go, polnode.go, prove.go, utils.go
=> utreexo: exporting detectOffset

utils.go, utils_test.go
subtreeRow returns how many rows the given subtree takes up in the passed in numLeaves.
=> utils: add subtreeRow

.github/workflows/go.yml, run_tests.sh
It wasn't really doing much to begin with. Removing since it's causing CI failures.
=> main: remove coveralls

prove.go, prove_test.go
genTTLs generates the ttls for all the deletions that are recorded in the CachingScheduleTracker.
=> prove: add genTTLs

prove.go, prove_test.go, testdata/fuzz/FuzzGenerateCachingSchedule/01555dbfff4187f1, testdata/fuzz/FuzzGenerateCachingSchedule/02cf2f41ece3eccd, testdata/fuzz/FuzzGenerateCachingSchedule/04f7dd6cbbf07c32, testdata/fuzz/FuzzGenerateCachingSchedule/05f9cfd60f4e2f74, testdata/fuzz/FuzzGenerateCachingSchedule/0bb87188e592beb4, testdata/fuzz/FuzzGenerateCachingSchedule/363ea095f7933047, testdata/fuzz/FuzzGenerateCachingSchedule/519e15dfe38c3c6a, testdata/fuzz/FuzzGenerateCachingSchedule/5485c369378dbe3c, testdata/fuzz/FuzzGenerateCachingSchedule/8bd811d87ba0dcbb, testdata/fuzz/FuzzGenerateCachingSchedule/90ef2493e5748879
GenerateCachingSchedule returns the positions that should be caching in
each block.
=> prove: add generate caching schedule

mappollard.go, mappollard_test.go
Removing as this info isn't needed for the outside caller as the stxo data already includes the height.
=> mappollard: remove createdHeight from MapPollard

prove.go
modifyInstruction is just two slices that represent the old hashes and the new hashes after a deletion has taken place. This function is useful during deletion of leaves.
=> prove: add modifyInstruction

prove.go
generateIngestAndUndoInfo adds a function that returns undoInfo and ingestInfo. With these two things, the caller can ingest a proof and/or perform an undo of the deletion that happened via the proof.
=> prove: add generateIngestAndUndoInfo
