accumulator.go, accumulator_test.go
Undo was not working correctly as Undo didn't add back the empty roots
that existed in the previous roots. This bug is now fixed.
=> accumulator: Fix Undo bugs

polnode.go, testdata/fuzz/FuzzModifyChain/04429001926f0a399c89a18b988e36d2a60f1f8776dd863a75da1465a1e39382
Setting polNodes to nil can result in memory leaks as polNodes with
aunts or nieces that aren't nil will not be garbage collected.
Calling delNode before setting the polNodes to nil solves this
problem.
=> polnode: Call delNode when setting nodes to nil

stump.go, stump_test.go, testdata/fuzz/FuzzStump/01bc37038b6b073f76c9d4409d8187b4c7e8554afa21e1df3cf9859fd6034bed, testdata/fuzz/FuzzStump/048292e84c3ef7c0aed0fb7412aaae2793023e2b5d1b69ef56076f0c7a8b8d98, testdata/fuzz/FuzzStump/0ee87bc92d2f5bbd55faa16d391b5e78db8939524eef53d4e835c4808d793ac6, testdata/fuzz/FuzzStump/112142eccd07dd64fc5fe8d8ab86519d22e7ce8d69a7c3df745cd87bfb036504, testdata/fuzz/FuzzStump/2a5d7ed53e5aeba0296a52d55398fa5546d076f0bd5bca8399d4cedd9bb947d7, testdata/fuzz/FuzzStump/2a6c803f7e2ac672897b2cb314c892a01769cf4a2f5f0371eaa55b7ec17b4230, testdata/fuzz/FuzzStump/37e2b941e80a6b2eebc0d40405277427b2e0c30bb52d70fb216648489b9b990b, testdata/fuzz/FuzzStump/3d765573e90565b85d76ff2f0e56cd21041a6e8deb0d03b3e63efcdb96ca9aa0, testdata/fuzz/FuzzStump/47d3c1e48717145171e5dae58a28a5d8169d41e3da81089ff43fbf86fcffe094, testdata/fuzz/FuzzStump/742636ec4ca45f012bb9aab7fc5c1182479f6e61bd2aa6c56ba0f7ce2ba63f5c, testdata/fuzz/FuzzStump/7af1341c69b9c75985874dad4df3ab45535527c79de53f77c11479b04b38986f, testdata/fuzz/FuzzStump/ad776931a0e0fe4c2f905ca63875e9684e885988609b92d04ed6ed6925df889d
Stump is a minimum required data needed for validating the accumulator
proofs. The advantages after that it doesn't have any of the
complexities that pollard has and is much simpler code-wise.
It seems that a user can keep track of proofs separately while using
stump to verify and update the accumulator state. Worth looking at as
it'll be much simpler than pollard.
=> Stump: Add new data structure called Stump

prove.go, stump.go
Not reversing saves and extra step and simplifies the code. Just handle
the roots being in smallest to largest order.
=> prove, stump: Don't reverse hashes in calculateRoots

prove.go
ToString is renamed to just String() as that is more in line with the
standard go library.
Also, the targets are not sorted before printing to show the targets in
their actual order.
=> Prove: Refactor Proof.String()

prove.go, utils.go
Returning computable positions is useful for implementations of proof
modifications. Computable positions were originally returned in the
github.com/mit-dci/utreexo repo before removing it as the returned
computable positions were not used. Adding it back in for the proof
modifications.
=> utils: Return computable positions in proofPositions()

prove.go
When root candidates do not match up with the pollard roots, print the
pollard roots and the root candidates in the error message.
=> prove: Improve error message for Pollard.Verify()

prove.go, prove_test.go, testdata/fuzz/FuzzGetMissingPositions/01c166e786e219b6deec1a8e5ea046e05c12b1899d89b840bd795bd3ef610fd7, testdata/fuzz/FuzzGetMissingPositions/023ae135ec56f116c0f4e369c7107400d2604f23ec29c91021a4f5e46b022daa, testdata/fuzz/FuzzGetMissingPositions/04312f074613cbe747957383671aea4b735700227abe10f9041afcdb3c13edeb, testdata/fuzz/FuzzGetMissingPositions/15ea06608dccf7ca0691dfb97f839c31a452e93ddd5474b374bc9f3ec88e5694, testdata/fuzz/FuzzGetMissingPositions/1ca1c4816003fbc18e98c0d303d5715846e5042d0589138edcb6550033879e78, testdata/fuzz/FuzzGetMissingPositions/3100b733d31ed5e6458dcdc2e5b5f2278a0e430d1746e8560aa888b91b6c59ea, testdata/fuzz/FuzzGetMissingPositions/53172a918f1b5cdfb5b97087d47e2549bbc38b8fc3d1f60db22eb6f75c4e62f8, testdata/fuzz/FuzzGetMissingPositions/671581e4e04b2b5110cefe141709c0dddedd8a00bee09d210fa082b853c27525, testdata/fuzz/FuzzGetMissingPositions/a58a50987de345c2c166708237bf6fec09e0803aa4bc9db3d4b0931cf81f12fa, testdata/fuzz/FuzzGetMissingPositions/c3bdf0cac21cec345d9668d1c5a87cb8c841d12cc3ab2d407c0f771466a9cd2c
GetMissingPositions() provides functionality for calculating the
positions you're missing to prove additional targets. This is useful
for mempool transactions relay as this allows for the peer to only
ask for certain un-cached positions instead of the entire proof.
There isn't code for constructing a proof from the missing positions
yet.
=> prove: Add GetMissingPositions()

prove.go, prove_test.go
Since the proof hashes were not being used, we can simply the function
signature of GetMissingPositions().
=> prove: Only request the targets in GetMissingPositions()

prove.go, prove_test.go, testdata/fuzz/FuzzRemoveTargets/02807a328b862070bbc09ce02ced5647513fc7e861d899abba9c906a6a0a80d3, testdata/fuzz/FuzzRemoveTargets/064b5ffb4f0fa0061017619d2d95ba0f9750dfa09dd361fd28aa2bb9c9373fc4, testdata/fuzz/FuzzRemoveTargets/1149ba4e20610722d3113ba26ca74d3970b8806cdfeb45069c535d78564a86cd, testdata/fuzz/FuzzRemoveTargets/1bd90df45f925e348802449d6c30202279111b12f74486b93570d6b7bb08db22, testdata/fuzz/FuzzRemoveTargets/1c28f8721c3628be29f55f4e02aed08ed3df1e3bc21fcc2cdd38a82b8bbed2ce, testdata/fuzz/FuzzRemoveTargets/4c3660f5945baa40787d7f4f7680021bfcc685e0e85ef6cae2a302363136e3ec, testdata/fuzz/FuzzRemoveTargets/65b55b79ec6de3f940c4b1662c9efa17b37991cb329bc96ad54ea6fb114f1fb3, testdata/fuzz/FuzzRemoveTargets/6a123fd1890f7ed3d3e540f8b9848deb1652df51cc55749730ed66dac7b7790e, testdata/fuzz/FuzzRemoveTargets/7e892cb72866a738c298d1a401467be85654010b6cabd5b5e01c1e821cd86229, testdata/fuzz/FuzzRemoveTargets/7f92a33e12d393b6adecc68fd63f8afc4704d925c20fa99977f4565643d2e71d, testdata/fuzz/FuzzRemoveTargets/8b6d2457ef9cef2290ee1ff76cf541e2db31b485519b2d6164e8e76b29c56e95, testdata/fuzz/FuzzRemoveTargets/8ec334e86aaf583140ef3c8cf3439bde7023399e642ce3f5c4e2d17d262d0833, testdata/fuzz/FuzzRemoveTargets/ad1e3fed9ba9f1ffd0c40e77c8719ae6ccd5d9c043a7757e42351b3a97eaa6c9, testdata/fuzz/FuzzRemoveTargets/b055c66716cb661b4b7fc35403f6b7b4081162809738d1bd0fbc854af302d11b, testdata/fuzz/FuzzRemoveTargets/c40751f3d2fb129f019254be8f60f8f54ef81a8164978474785460fbfcdda1e9, testdata/fuzz/FuzzRemoveTargets/c40fd7bd756565ddd87b26798066184f3e971cdbe64aa4564dfd9bdbc501ad15, testdata/fuzz/FuzzRemoveTargets/cbcc67976d106726f1e9f980baca05c32c7a40ca04d2789fc223e1a48514ccab
RemovePositions() allows for the removal of desired slice of positions
from the proof. This is useful for un-caching of leaves after they're
deleted. For Bitcoin wallets, this will be useful when deleting stxos
from the cached proof.
=> prove: Add RemovePositions()

prove.go, prove_test.go
The responsibility of removing the deleted hashes was on the caller
since RemoveTargets() would only remove the targets from the proof.
RemoveTargets() has enough information to also return the modified
delHashes so the function signature is changed to do so.
=> prove: Return delHashes in RemoveTargets()

prove.go, prove_test.go, utils.go
AddProof takes proofA and proofB and returns a merged proofC. The proofC
contains deduped targets of proofA and proofB.
=> prove: Add AddProof() function

prove.go, prove_test.go, testdata/fuzz/FuzzUpdateProofRemove/01298cc488ff878b0ac18a3ed9f770f218acdcfac78a886d2df3f04e54aaf717, testdata/fuzz/FuzzUpdateProofRemove/01767920f4491ac9b1449930b186669c1651decaf56042734fe3035f752b7f02, testdata/fuzz/FuzzUpdateProofRemove/018d9d4abb09df7b7fa66d447312a2f8ec2b6bf86b36b2402cba4747349022b0, testdata/fuzz/FuzzUpdateProofRemove/07198aada44c542dae10710ccd59419e2ae3a7ab0e2021e457f423daff5d0c3e, testdata/fuzz/FuzzUpdateProofRemove/9228179161ad9e9b7216e3b7ccf15bcaced8fe9b7e98e930cb6cc1c05d41a0fe, testdata/fuzz/FuzzUpdateProofRemove/975b2b858339762e6373e9de37e134dedd7ab22372f5ecaefb175ce236f64161, testdata/fuzz/FuzzUpdateProofRemove/d0b4fb38fd06de873da4fc047233d9b05cf6da02494fac8414ceb7e219a502c2, testdata/fuzz/FuzzUpdateProofRemove/ee3cbb0fe479ecbd38e2f06fd1c354d1a2b4ecfefb339bd5c452a932e48a18b4, testdata/fuzz/FuzzUpdateProofRemove/f1bdbd8604c0c92bd55b6c3c0f8d07ed7ac8aaeb91b648e7a31241269f1857b4
UpdateProofRemove provides functionality for updating the cached proof
with a block proof. The returned hashes and proof will be proving the
targets that were not deleted from by the block proof.
This functionality is useful for Bitcoin wallets and Bitcoin nodes that
maintain a mempool.
=> prove: Add UpdateProofRemove

utils.go
Giving the same positions in isAncestor would return true. This *can*
result in bugs for some edge cases as if you attempted to call
calcNextPosition after checking for ancestor-ness with isAncestor, its
behavior would be undefined since the ancestor check is incorrect.
=> utils: isAncestor bug fix

prove.go, prove_test.go, testdata/fuzz/FuzzUpdateProofAdd/0d82cc561b6b4f508eab1125bde23e3f751e4923f335b6b51d09bbcf57450ee9, testdata/fuzz/FuzzUpdateProofAdd/35230858d13aa8ffe466a6258e70e282cc54b2468e09d75b6d2b95ac00a08da3, testdata/fuzz/FuzzUpdateProofAdd/3d97223d357ea343991fae926e700828b4ae6134c9772f95f52b7aa22c9c7efd, testdata/fuzz/FuzzUpdateProofAdd/408890dd4dc94028f06996744c8edb4a418ae68fcb345979e1c98f5a8666b798, testdata/fuzz/FuzzUpdateProofAdd/814dea3693871172e625be3fa95a58c30ce320f6f31611e66e535159ad99f3ca, testdata/fuzz/FuzzUpdateProofAdd/922490e8cf312f31194c1ddfba3860ebce13eee0128efb8735aadd842a263ee3, testdata/fuzz/FuzzUpdateProofAdd/a372ba6f0a8a927ccb5a8baa799771f336563a670a9d101bc1a244bb59f719d2, testdata/fuzz/FuzzUpdateProofAdd/b9ccb15d9585a38e612e3507caf91bb6cbf0e869f5842ef5430eb1d7afd428a6, testdata/fuzz/FuzzUpdateProofAdd/bc69874923e2d32bc9ac0362a907969d627d245b3d8f72eb6baf5328715c9f83, testdata/fuzz/FuzzUpdateProofAdd/d74d552aff1588f4e74f5b159dad29d1445ae608b2abe0ebd2729f254f9d9310
UpdateProofAdd modifies the given cached proof to add the extra
necessary hashes after new leaves have been added to the accumulator.
Use cases for this are for wallets and mempool where the proof for
existing cached leaves will need to be modified when a block or tx comes
in.
=> prove: Add UpdateProofAdd

accumulator.go, accumulator_test.go, polnode.go, polnode_test.go, prove.go, prove_test.go, stump_test.go, utils.go
Exporting pollard fields allow the caller to make functions such as serialization. This is important as it leaves the complexity/flexibility to the callers for additional functions they may need.
=> accumulator: Export pollard fields

prove.go, prove_test.go, utils.go
Previously the corresponding hash and pos would have to be combined into
a slice of hashAndPos and later split into two slices of []uint64 and
[]Hash.
The new hashAndPos is just the slice of []uint64 and []Hash
that's combined into one struct, eliminating the need to allocate new
slices.
=> prove: Implement more memory efficient hashAndPos

prove.go, prove_test.go, testdata/fuzz/FuzzGetProofSubset/02b9269ace179dd23ee9fb86b96ae932c446985cba5b4e39e5c51abc57b0e907, testdata/fuzz/FuzzGetProofSubset/18374851657a78e8a6bba9961dd17c129b3a1039797ced120960a8c0249b289a, testdata/fuzz/FuzzGetProofSubset/7f73a8fe20f50afe045589f9a035d7da53f0520e73b5778099e46d0253daa885
If a node has a proof for targets [0, 1, 2] but only wants to prove to
someone that [0] exists in the accumulator, GetProofSubset can be used
to create a proof that's only for that specific target.
This is useful for mempool and wallets alike.
=> prove: Add GetProofSubset

prove_test.go, stump.go, stump_test.go
The newer stump functions result in simpler function prototypes and
allows for more succinct calls to Update().
=> stump: Refactor functions into methods

prove.go, stump.go
The changes made to calculateRoots() now enables support for calculating
the roots that happen after a deletion. This replaces the functionality
that proofAfterDeletion() along with the old calculateRoots() provided
for stump deletion. The deletion is now just M*log(N) where N = number of
leaves and M = number of targets.
=> Prove: Modify calculateRoots() to support deletions

prove.go
Refactor of the calculateRoots() function so that the overall code is simpler.
This PR also helps with performance as well since the allocation that used
to happen in mergeSortedHashAndPos is avoided now.
=> prove: Refactor calculate roots

prove.go, utils.go
Calling delete for hashAndPos in calculateRoots made too many calls to
runtime.memmove, resulting in extremely slow ibd. The newly added
functions Pop and Popfront will provide a function that will pop without
moving data around.
=> prove: Faster calculateRoots

prove.go, stump.go
calculateRoots is refactored to calculateHashes to support returning of the intermediate hashes that were calculated when hashing up to the root.
This is useful for updating cached proofs.
=> prove: Refactor calculateRoots to calculateHashes

accumulator.go, accumulator_test.go, testdata/fuzz/FuzzUndoChain/086b149d35967288d87b31db61a9f99c79c3dc72807ec2f2ea2d9376c86dcd24, testdata/fuzz/FuzzUndoChain/313ce4d7bf60758570d2c9edd0d6f3a24ad55c76396989052d232a0cbe91118b, testdata/fuzz/FuzzUndoChain/a06ddeb31e4501a9152f97f96b0f36db70336d924fbf520870904e15650fc30b, testdata/fuzz/FuzzUndoChain/df15c4fff25f3d16d0f4135cc53a0be62f6b3a5db855e5d7358ef2cdc68d33fa
Undo empty roots would place the empty roots at the wrong row. The bug is addressed and the new tests are now able to detect the bug.
=> accumulator: Fix undo empty roots bug

utils.go
treeRows() is changed to a much simpler algorithm that only depends on
counting the number of bits used to represent the number of leaves.
Since only numLeaves of 2^n should decrement in the number of bits used,
the function should return the correct amount of total rows except 0
(which is handled separately).
This changed is based off of https://github.com/utreexo/pytreexo/pull/3
=> utils: Simplify treeRows()

prove.go, prove_test.go, testdata/fuzz/FuzzUndoProof/01853711f927b17c02e19316cf9ea197124ee86043f9be3fe7bd52522ce501c5, testdata/fuzz/FuzzUndoProof/0e9c0513e919640f150559eedd7d19307fdc946e19163a91a545017e579b2024, testdata/fuzz/FuzzUndoProof/140bd15169f4cf10a8b5f673e47f7d1c5b11e77675dd2a53874d28e21ecfacb8, testdata/fuzz/FuzzUndoProof/18a022239c92a4d9e418c4b774a79fbf52d5308fe33dd2b62bfdfb3df5a290d4, testdata/fuzz/FuzzUndoProof/25b81c7cb4332ccff0c443dcef9481cfb9b8867e89a22de4767c54b7e012d550, testdata/fuzz/FuzzUndoProof/546f4737ff1b6b8035d7275ff6b980ebdb39b5cca4388b82860320c0c5e21ab5, testdata/fuzz/FuzzUndoProof/54abe0f674696bfb1db6b4445480aa910908f7cbf15d13ee36d4e3690c4858be, testdata/fuzz/FuzzUndoProof/55755dd7baf7e39fc0ce6c4793596846a5142f8d57bf786fd18d17efd7e72d48, testdata/fuzz/FuzzUndoProof/69221dc8f7c85dc2102e963299b51500a5d6fae678d9bd9c430f04086cbd0f54, testdata/fuzz/FuzzUndoProof/b0909325fa61dbdbc588cbc323fe96335f9caeed2250739018e0f0adb37f1773, testdata/fuzz/FuzzUndoProof/b30f3a73f7f35321153dfdeae0677219a68c85f50457eea3605e3a28187cc3d4, testdata/fuzz/FuzzUndoProof/fabca76b212d59611a64848edeedf4efe6102bee977667e3790ec983f6f19479, testdata/fuzz/FuzzUndoProof/fce4674243343aee26b11ca90401422f25afb13e917bba6ad757ed63dfaa71cf, testdata/fuzz/FuzzUndoProof/fe1c0e84757195f70e3f73fbe97857cc74c403969fe1fbc4006127b3d51eadb4, testdata/fuzz/FuzzUndoProofChain/33c6d3da60e06554fe514308aae30f5aa4839139bccc061e8e7a324c9c012f53, utils.go
Cached proof are meant for wallets to be able to keep track of their own
utxos. Wallets must be able to reorg back blocks which means that the
cached proofs need to support undoing.
The Undo function mimics that of the Bitcoin Core wallet where the
reorging of a block where a spend occured doesn't automatically re-add
back the spent utxo. That must be done separately.
=> prove: Add support for undoing cached proofs

utils.go
Note that there are also some string creation functions that are currently unused (`AllSubTreesToString`, `polNodeAndPosToString`), but I assume that those could be very handy in the course of debugging, adding verbose testing messages etc.
=> utils: Remove unused functions `logicalTreeRows`,`rowLength`,`extractRow`

prove.go
Another small remove-only cleanup PR. `hashSiblings` hasn't been used since commit 9aa42b5ecd2bf799e769233c1ea0c18f45962c02 ("prove: Remove unused RemoveTargets") and hence can be removed.
=> prove: Remove unused function `hashSiblings`

utils.go, utils_test.go
childMany allows for calculating a descendant without having to call leftChild or rightChild numerous times.
=> accumulator/utils: Add childMany

utils.go, utils_test.go
translatePos is useful for when translating a given position to a different total rows. There are some implementations that benefit from pre-allocating rows. For these implementations, a given position may differ in value if it's not in row 0.
The below illustrates how the positions would differ in different pre-allocated total rows. position 2 in totalrows=1 would be position 4 if totalrows=2.
```
02
|---\
00  01
|-------\
04
|---\   |---\
00  01
```
=> utreexo/utils: Add translatePos

accumulator_interface.go, accumulator_interface_test.go, pollard.go, pollard_test.go, polnode_test.go, prove.go, prove_test.go, stump_test.go
The Utreexo interface defines a set of methods that all utreexo
implementations should abide by.
This allows for callers to easily switch between different Utreexo
implmentations as well as allowing for code reuse for different
tests.
=> Add utreexo interface

pollard.go, prove.go, utils.go, utils_test.go
The totalRows argument in isRootPosition depended on the totalRows being the minimum possible for the numleaves. For example, it's possible to have a numleaves of 1 but have a totalRows of 50.
However, for isRootPosition to work correctly, totalRows always needed to equal treeRows(numLeaves). This meant that if you gave position=0, numleaves=1, totalRows=50, isRootPosition would return false even though it should return true.
Because of this, isRootPosition and isRootPositionOnRow is changed to only take in the numleaves to avoid future bugs.
=> utreexo: Avoid potential bug with isRootPosition

utils.go
translatePositions is a wrapper around translatePos that translates a slice of positions instead of a single position.
=> utreexo/util: Add translatePositions

utils.go, utils_test.go
proofPosition allocates less memory than proofPositions when the caller only needs the proof positions for a single position.
=> utreexo/utils: Add proofPosition

pollard.go, utils.go
Refactoring getLowestRoot to take in totalRows allows for callers to get the lowest root of any arbitrary totalRows instead of the one that's calculated by treeRows.
=> utreexo/pollard,utils: add totalRows arg to getLowestRoot

utils.go
The longest a proof can be is totalrows+1 per targets. The proof positions and proof position functions are changed so they allocate exactly that much.
=> utreexo/utils: make proofPositions only allocate once

polnode.go
Useful as when printing, it'll print the hex string instead of the unreadable slice of uint8s.
=> utreexo/polnode: add String for Hash

polnode.go
Adding String to leaf allows it to be pretty-printed when passed in to be printed with %v.
=> utreexo/polnode: add String to Leaf

mappollard.go, mappollard_test.go, prove.go, prove_test.go, stump.go, stump_test.go
Previously the go runtime was able to throw a panic on an invalid proof if the proof length was not long enough. This is obviously undesirable and this commit now adds a check to make sure that the proof length cannot make the entire program panic.
=> prove: return error when proof is short

mappollard.go
We're checking if the m.TotalRows is allocating more than what treeRows(m.NumLeaves) requires.  The comparison was incorrect and it's changed to != since the treeRows(m.NumLeaves) can never be smaller than m.TotalRows anyways.
=> mappollard: fix trimProof if condition

pollard.go, pollard_test.go
GetLeafHashPositions provides a method for bridge nodes to fetch positions for the inputs of a transaction in the mempool.
=> pollard: add getleafhashpositions

mappollard.go
GetLeafHashPositions provides a method for compact state nodes to fetch positions for the inputs of a transaction in the mempool. This allows for propagation of txs for the csns.
=> mappollard: add getleafhashpositions

mappollard.go, stump.go
During ibd, the functions that provided functionality for merging sorted slices were extremely memory wasteful. Switching to a map was much more efficient based on ibd profiling.
=> stump, mappollard: Avoid using mergeSorted*

mappollard.go
The maximum amount of total rows that we can have is 2**64 as the max position we can have with uint64 is within the bounds of 2**64 utreexo tree. 50 is kind of a random number anyways, why not make it a max.
=> mappollard: increase the pre-allocated totalrows

mappollard.go
Adding a convenient function to initialize a mappollard from a certain root+num leaves. Since mappollard requires calling other functions to calculate the positions of the leaves, this is just a more convenient function to call.
=> mappollard: add NewMappollardFromRoots

mappollard.go, mappollard_test.go
The change to interface here allows for callers to give different storages for the mappollard. This is mostly so that utreexo nodes in utreexod can use on-disk storage instead of having the entire merkle forest in memory.
=> mappollard: change map to interface

accumulator_interface.go, mappollard.go, pollard.go, pollard_test.go
The newly added interface will allow for bridge nodes to fetch positions for leaves so that the positions can be broadcast to utreexo peers.
=> accumulator_interface: add GetLeafPosition to the interface

mappollard.go, pollard_test.go
The returned position from GetLeafPosition was the untranslated internal position, which is different from the actual position. Fixes the bug and adds a test.
=> mappollard: translate positions on GetLeafPosition

utils.go
For startPositionAtRow, calculated offset variable was an int which was being casted to uint64. This would overflow on 32bit systems and so we make sure we always use uint64 and don't let the value be int.
=> utils: fix 32 bit system bug

mappollard.go, pollard_test.go
On add, when we're on hashing against a zombie root, sometimes that zombie root would stay dangling around and overwrite other nodes on moveUpDescendents. We make sure that we remove the zombie root to avoid this bug.
=> mappollard: make sure to remove dangling empty root on add

mappollard.go
When calling GetHash, callers would do so through the position of the accumulator when it's the minimum amount of treerows possible. Since interally mappollard may have more rows allocated, make sure to translate the position.
=> mappollard: translate position on GetHash

mappollard.go, mappollard_test.go, prove.go, prove_test.go, stump_test.go, utils.go, utils_test.go
proofpositions is needed for the new block download protocol that
requires the client to compute for which proof positions it needs.
Exporting gives utreexod the ability to call it.
Simplifying is just cherry on top and prevent possible infinite loop bugs.
=> utils: simplify and export proofpositions

mappollard.go, prove.go, prove_test.go, utils.go
In an attempt to use `utreexod` as a chain backend in `lnd`, this error popped up,
```
.../utreexo/utils.go:952:29: type func(a E, b E) bool of less does not match inferred type func(a E, b E) int for func(a E, b E) int
```
Found the cause here:
> It turns out that a commit landed in [golang.org/x/exp](https://github.com/golang/exp/tree/master/slices) which changes the signature of the sorting functions, and breaks backward compatibility
More info can be found in this [answer](https://stackoverflow.com/questions/77275713/t-less-does-not-match-inferred-type-funca-t-b-t-int-for-funca-e-b-e-int).
The fix is simple, that we use `slices` from the standard lib instead.
=> utreexo: use `slices` from standard lib

.github/workflows/go.yml, go.mod, pollard_test.go, run_tests.sh, utils.go
The usage of slices package as a standard library was introduced in go v0.21.0. Updating the package so we have access to the library.
=> main, .github: update to go 0.21.1

prove.go
For reflect.DeepEqual(), it won't equal if the proof slice is nil vs empty. Since by default it's nil, don't init unless if there's a need.
=> prove: don't allocate proof slice if it's empty

mappollard.go, mappollard_test.go, pollard.go, pollard_test.go, polnode.go, prove.go, prove_test.go, stump.go, stump_test.go, utils.go, utils_test.go
treeRows is exported as it's required for clients that are calculating which proof positions they need to download.
=> utreexo: export treeRows

go.mod, go.sum, prove.go, prove_test.go, testdata/fuzz/FuzzAddBlockSummary/022a498bd055a925, utils.go
CachingScheduleTracker takes in block summary information and is able to
generate a clairvoyant caching schedule. The code included here is the
code for taking in block summaries and generating the zombie root
information.
=> prove, testdata: add caching scheduler

prove.go, prove_test.go, testdata/fuzz/FuzzGetPrevPos/006c26a74154d611, testdata/fuzz/FuzzGetPrevPos/19a57a9acf324b37, testdata/fuzz/FuzzGetPrevPos/5de3dd5bd991236d, testdata/fuzz/FuzzGetPrevPos/791bb5f4000a1a44, testdata/fuzz/FuzzGetPrevPos/b870be6781b1f1b1
Because we go backwards, we must be able to calculate the original positions of the deletions. The following code is added here.
=> prove: add undo code for []uint64

mappollard.go, mappollard_test.go, testdata/fuzz/FuzzMapPollardTTLs/c369cd12dfc951ce
For bridge nodes, caching leaves with their creat height and index is useful
for generating TTLs for additions. The added methods `ModifyAndReturnTTLs`
and `UndoWithTTLs` allow callers to take advantage of the added in LeafInfo
for each of the cached leaves.
=> mappollard: add LeafInfo for the cached leaves

mappollard.go, mappollard_test.go
This solves an off by one error that happens for the caller of ModifyAndReturnTTLs and UndoWithTTLs
=> mappollard: change currentModifies to currentHeights

mappollard.go
Since it's not possible to keep a full forest if you're initializing from roots, we remove the option from the function.
=> mappollard: remove full boolean from NewMapPollardFromRoots

mappollard.go
This is a new type of a Node that will be used to represent the
mappollard. It has all the data in it for you to traverse up and down
the pollard.
The view represents a part of the mappollard with all the roots. When
something is removed from the view, its key is stored in the removed
slice.
The view mainly serves as a buffer to avoid lookups from the main map
which is slow since its so big. However, it also has the added benefit
of making removes atomic in mappollard.
=> mappollard: introduce node type
